// Mocks generated by Mockito 5.4.6 from annotations
// in todo_list_app/test/features/todoList/data/repository/todo_list_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_list_app/features/todoList/data/datasource/todo_list_local_datasource.dart'
    as _i3;
import 'package:todo_list_app/features/todoList/data/models/todo_list_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTodoListModel_0 extends _i1.SmartFake implements _i2.TodoListModel {
  _FakeTodoListModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoListLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoListLocalDataSource extends _i1.Mock
    implements _i3.TodoListLocalDataSource {
  MockTodoListLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TodoListModel>> getAllTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTodos, []),
            returnValue: _i4.Future<List<_i2.TodoListModel>>.value(
              <_i2.TodoListModel>[],
            ),
          )
          as _i4.Future<List<_i2.TodoListModel>>);

  @override
  _i4.Future<_i2.TodoListModel> addTodo(_i2.TodoListModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [todo]),
            returnValue: _i4.Future<_i2.TodoListModel>.value(
              _FakeTodoListModel_0(this, Invocation.method(#addTodo, [todo])),
            ),
          )
          as _i4.Future<_i2.TodoListModel>);

  @override
  _i4.Future<bool> removeTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeTodo, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.TodoListModel> toggleTodoComplete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTodoComplete, [id]),
            returnValue: _i4.Future<_i2.TodoListModel>.value(
              _FakeTodoListModel_0(
                this,
                Invocation.method(#toggleTodoComplete, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.TodoListModel>);

  @override
  _i4.Future<_i2.TodoListModel?> getTodoById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodoById, [id]),
            returnValue: _i4.Future<_i2.TodoListModel?>.value(),
          )
          as _i4.Future<_i2.TodoListModel?>);
}
