// Mocks generated by Mockito 5.4.6 from annotations
// in todo_list_app/test/features/todoList/domain/usecases/todo_list_get_all_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_list_app/core/errors/failures.dart' as _i4;
import 'package:todo_list_app/features/todoList/domain/entities/todo_list_entity.dart'
    as _i5;
import 'package:todo_list_app/features/todoList/domain/repository/todo_list_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TodoListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoListRepository extends _i1.Mock
    implements _i2.TodoListRepository {
  MockTodoListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.Failure?, List<_i5.TodoListEntity>?)> getAllTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTodos, []),
            returnValue:
                _i3.Future<(_i4.Failure?, List<_i5.TodoListEntity>?)>.value((
                  null,
                  null,
                )),
          )
          as _i3.Future<(_i4.Failure?, List<_i5.TodoListEntity>?)>);

  @override
  _i3.Future<(_i4.Failure?, _i5.TodoListEntity?)> addTodo(
    _i5.TodoListEntity? todo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTodo, [todo]),
            returnValue: _i3.Future<(_i4.Failure?, _i5.TodoListEntity?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.Failure?, _i5.TodoListEntity?)>);

  @override
  _i3.Future<(_i4.Failure?, bool?)> removeTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeTodo, [id]),
            returnValue: _i3.Future<(_i4.Failure?, bool?)>.value((null, null)),
          )
          as _i3.Future<(_i4.Failure?, bool?)>);

  @override
  _i3.Future<(_i4.Failure?, _i5.TodoListEntity?)> toggleTodoComplete(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTodoComplete, [id]),
            returnValue: _i3.Future<(_i4.Failure?, _i5.TodoListEntity?)>.value((
              null,
              null,
            )),
          )
          as _i3.Future<(_i4.Failure?, _i5.TodoListEntity?)>);
}
